export const ADD_MESSAGE = 'ADD_MESSAGE'
export const GET_MESSAGES = 'GET_MESSAGES'
export const LOGIN = 'LOGIN'

export const OPEN_CHATROOM = 'OPEN_CHATROOM'
export const OPEN_CHATROOM_SUCCESS = 'OPEN_CHATROOM_SUCCESS'
export const OPEN_CHATROOM_FAILED = 'OPEN_CHATROOM_FAILED'

export const JOIN_CHATROOM = 'JOIN_CHATROOM'
