export const ADD_MESSAGE = 'ADD_MESSAGE'
export const GET_MESSAGES = 'GET_MESSAGES'
export const SET_PERSONA = 'SET_PERSONA'

export const CREATE_CHATROOM_START = 'CREATE_CHATROOM_START'
export const CREATE_CHATROOM_SUCCESS = 'CREATE_CHATROOM_SUCCESS'
export const CREATE_CHATROOM_FAILED = 'CREATE_CHATROOM_FAILED'

export const LOAD_CHATROOM_START = 'LOAD_CHATROOM_START'
export const LOAD_CHATROOM_SUCCESS = 'LOAD_CHATROOM_SUCCESS'
export const LOAD_CHATROOM_FAILED = 'LOAD_CHATROOM_FAILED'

export const JOIN_CHATROOM_START = 'JOIN_CHATROOM_START'
export const JOIN_CHATROOM_SUCCESS = 'JOIN_CHATROOM_SUCCESS'
export const JOIN_CHATROOM_FAILED = 'JOIN_CHATROOM_FAILED'

export const SEND_MESSAGE_START = 'SEND_MESSAGE_START'
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'
export const SEND_MESSAGE_FAILED = 'SEND_MESSAGE_FAILED'
export const SORT_MESSAGES = 'SORT_MESSAGES'
